version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    container_name: ros-humble-dev
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./ros2_ws:/ros2_ws
    network_mode: host
    stdin_open: true
    tty: true
    command: bash

  run:
    build:
      context: .
      dockerfile: Dockerfile
      # platform: linux/arm64/v8
      # platform: linux/arm/v7
      target: runtime
    container_name: ros-humble-run
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - ./ros2_ws/install:/app/install:ro
      - ./ros2_ws/src:/app/src:ro
    network_mode: host
    privileged: true
    command: bash -c "source /app/install/setup.bash && ros2 run your_package your_node"
    depends_on:
      - dev